### ISSUE TITLE
Should we introduce functions for conditionally setting html?

### ISSUE THREAD

**Issue by matthewdunsdon** [zambezi/d3-utils#14]
:thought_balloon:  Often when writing d3 components; it is helpful to think about conditionally setting content, either when component is known to be given an empty DOM node or when component needs to replace to content of a DOM node.

## Expected Behaviour

:new: Potential function for only setting content is selection is empty:

```javascript
export function setContentIfEmpty(template) {
  return function setContent (s) {
    if (!s.node().hasChildNodes()) {
      s.html(template)
    }
  }
}
```

:new: Potential function for only setting content is selector has not matches:

```javascript
export function setContentIfMissing (content, selector) {
  return function setContent (s) {
    if (s.select(selector).empty()) {
      s.html(content)
    }
  }
}
```

## Context

:speaking_head: I was hoping that adding this functionality to the d3-utils library, so that I can write readable and maintainable code.  If there are better ways of thinking about the conditional content rendering, then I am open to alternative ideas.

:incoming_envelope:  I would be happy to submit a PR if we think this is a good idea.

**Comment by mstade** [comment]
@gabrielmontagne – penny for your thoughts?

**Comment by gabrielmontagne** [comment]
hello, this is useful : )

we have a cousin of this future components in https://github.com/zambezi/d3-utils/blob/master/man/append-if-missing.md, which can be used in `select(` operations and will return the potentially new element, so that you can chain and operate on it straight away.

```
const ourtTitleWithClasses = appendIfMissing('h1.hey-matt')

// .. .somewhere further down, 

s.select(ourDivWithClasses).text('first time this is new')  // the text is set on the h1, no need to re-select
s.select(ourDivWithClasses).text('second time this is the same')
```

Would it make sense to make the new component run along thse lines?

**Comment by matthewdunsdon** [comment]
:confused:  I am not sure I understand how to make this run alongside append-if-missing.

-----

It would be worth clarifying, when I am talking about content or templates, I am talking about strings containing HTML.

So let us take a look at a fictitious example.:

```javascript
const helloTemplate = `<div><h1 class="hello-greeting-title">Say hello</h1>
<label>Name: <input type="text" name="name" /></label>
</div>`
const setContent = setContentIfMissing(helloTemplate, '.hello-greeting-title')

export function createHelloGreeting () {
  return helloGreeting
  function helloGreeting (s) {
    // At this point I do not know what state the selection 's' is in.
    // I only want to clear the selector and set the content to my templae if can not find '.hello-greeting-title'
    s.call(setContent)
       .select('.input')
       .call(setInputValidation)
    // ...
  }

  function setInputValidation (s) {
    //...
  }
}
```

----

If we had to use the existing functions we could so something like

```javascript
//...
   if (s.select('.hello-greeting-title').empty()) {
     s.html(helloTemplate)
   }
   s.select('.input')
     .call(setInputValidation)
//...
```

One option would be to make this more like append-if-missing by allowing it to be invoked via a select call:
```javascript
//...
    s.select(setContent)
     .select('.input')
     .call(setInputValidation)
//...
```

I do not have a preference as to whether we use `.call(...)` or `.select(...)`.  If `select` is more in-line with other functions in d3-utils, then I can take that approach.

**Comment by gabrielmontagne** [comment]
I see what you're saying. 

What I meant was that -- and I'm not 100% sure this makes sense -- if we select and pass the component in, if something is obviously (or at least likely) to be the new selection on which we operate, then we could return it, so that you can use it in a chained expression without having to select manually.

so, following your example, if we have,

```
const greetingTitle = setContentIfMissing(helloTemplate, '.hello-greeting-title')
```

One could assume (or at least not be surprised if) when you do this,

```
someSelection.select(greetingTitle).text('hey title')
```

... the text would be set on that element which had the `.hello-greeting-title` class?

If for whatever reason that was just something you use to mark the template, but still you wanted to keep operating on `someSelection`, the same component would very well work if you called it like this,

```
someSelection.each(greetingTitle)  // returns still someSelection
    .select('.something-else')     // again from the top level
    .text('this text is perhaps not on the greeting title')
```

How would something like that sound?

**Comment by matthewdunsdon** [comment]
That sounds good to me.

**Comment by matthewdunsdon** [comment]
@gabrielmontagne What do we think `setContentIfEmpty` should return as a node?

The options appear to be:

1. Return the current node
2. Return the first child node

My thoughts are that it should return the first child node.

**Comment by gabrielmontagne** [comment]
Hi, yes,  I think it should return the first node _that matches the
provided selector_.  it should return that new node so that the continued
selector operations work on it, not on the top selection.
